language:
  node_js
node_js:
  - "stable"
addons:
    code_climate:
        repo_token:772d02e6d14eb53a10f73abbd6e9cdd47716c3d3a81392693805872a973b386c
after_success: 'npm run coveralls'
script: npm test
before_script:
  - npm install codeclimate-test-reporter istanbul -g
  - psql -c '\conninfo'
after_script:
  - codeclimate-test-reporter < ./coverage/lcov.info
services:
  - postgresql
addons:
  hosts: travis.dev
